# Generated by Django 5.2.6 on 2025-09-26 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('competitor_names', models.TextField(blank=True, help_text='Optional: other names this SKU might appear as.')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_selector', models.CharField(help_text="CSS selector for current price (e.g., '.price_color')", max_length=255)),
                ('promo_price_selector', models.CharField(blank=True, help_text='CSS selector for promo price if any', max_length=255)),
                ('promo_text_selector', models.CharField(blank=True, help_text='CSS selector for promo text/badge', max_length=255)),
                ('retailer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='pricing.retailer')),
            ],
        ),
        migrations.CreateModel(
            name='SKUListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='pricing.retailer')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='pricing.sku')),
            ],
            options={
                'unique_together': {('sku', 'retailer', 'url')},
            },
        ),
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promo_text', models.CharField(blank=True, max_length=255)),
                ('raw_currency', models.CharField(blank=True, max_length=10)),
                ('raw_snapshot', models.TextField(blank=True, help_text='Optional: raw extracted text for audit/debug')),
                ('sku_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='pricing.skulisting')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
